#!/bin/bash
## Octave-Forge dicom package bootstrap script
## Run this to generate the configure script

set -e      # halt if unhandled error

aclocal -Im4 # gather the CMAKE_FIND_PACKAGE
autoconf    # generate configure script
