#!/bin/bash
## Octave-Forge dicom package bootstrap script
## Run this to generate the configure script

set -e      # halt if unhandled error

aclocal
autoconf    # generate configure script
autoheader -f
